version: '3.8'

services:
  phonova:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - N8N_URL=https://n8n.phonova.ai
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./sessions:/app/sessions
    networks:
      - app-network
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=n8n.phonova.ai
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - N8N_URL=https://n8n.phonova.ai
      - N8N_USER_MANAGEMENT_DISABLED=true
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_HIRING_BANNER_ENABLED=false
      - N8N_EMAIL_MODE=smtp
      - N8N_SMTP_HOST=smtp.gmail.com
      - N8N_SMTP_PORT=587
      - N8N_SMTP_USER=your_email@gmail.com
      - N8N_SMTP_PASS=your_app_password
      - N8N_SMTP_SENDER=your_email@gmail.com
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  n8n_data:
